CREATE TABLE `ai_job_attempts` (
	`id` text PRIMARY KEY NOT NULL,
	`job_id` text NOT NULL,
	`attempt_number` integer NOT NULL,
	`worker_id` text NOT NULL,
	`lease_generation` integer NOT NULL,
	`started_at` integer NOT NULL,
	`last_heartbeat_at` integer,
	`completed_at` integer,
	`outcome` text NOT NULL,
	`safe_error_code` text,
	`retry_scheduled_at` integer,
	FOREIGN KEY (`job_id`) REFERENCES `ai_jobs`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "ai_job_attempts_number_valid" CHECK("ai_job_attempts"."attempt_number" between 1 and 100),
	CONSTRAINT "ai_job_attempts_worker_valid" CHECK(length(trim("ai_job_attempts"."worker_id")) between 1 and 200),
	CONSTRAINT "ai_job_attempts_generation_valid" CHECK("ai_job_attempts"."lease_generation" >= 1),
	CONSTRAINT "ai_job_attempts_started_nonnegative" CHECK("ai_job_attempts"."started_at" >= 0),
	CONSTRAINT "ai_job_attempts_heartbeat_valid" CHECK("ai_job_attempts"."last_heartbeat_at" is null or "ai_job_attempts"."last_heartbeat_at" >= "ai_job_attempts"."started_at"),
	CONSTRAINT "ai_job_attempts_completed_valid" CHECK("ai_job_attempts"."completed_at" is null or "ai_job_attempts"."completed_at" >= "ai_job_attempts"."started_at"),
	CONSTRAINT "ai_job_attempts_outcome_valid" CHECK("ai_job_attempts"."outcome" in ('RUNNING','SUCCEEDED','RETRYABLE_FAILURE','NON_RETRYABLE_FAILURE','TIMED_OUT','LEASE_EXPIRED','CANCELLED')),
	CONSTRAINT "ai_job_attempts_error_valid" CHECK("ai_job_attempts"."safe_error_code" is null or length(trim("ai_job_attempts"."safe_error_code")) between 1 and 120),
	CONSTRAINT "ai_job_attempts_retry_time_valid" CHECK("ai_job_attempts"."retry_scheduled_at" is null or "ai_job_attempts"."retry_scheduled_at" >= "ai_job_attempts"."started_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ai_job_attempts_job_number_unique` ON `ai_job_attempts` (`job_id`,`attempt_number`);--> statement-breakpoint
CREATE INDEX `ai_job_attempts_job_index` ON `ai_job_attempts` (`job_id`,`started_at`);--> statement-breakpoint
CREATE TABLE `ai_jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`payload_version` integer NOT NULL,
	`payload_json` text NOT NULL,
	`payload_hash` text NOT NULL,
	`dedupe_key` text NOT NULL,
	`cost_center` text NOT NULL,
	`cost_operation_id` text,
	`priority` text NOT NULL,
	`status` text NOT NULL,
	`attempt_count` integer DEFAULT 0 NOT NULL,
	`max_attempts` integer NOT NULL,
	`timeout_ms` integer NOT NULL,
	`lease_duration_ms` integer NOT NULL,
	`backoff_base_ms` integer NOT NULL,
	`backoff_max_ms` integer NOT NULL,
	`scheduled_at` integer NOT NULL,
	`lease_owner` text,
	`lease_token` text,
	`lease_generation` integer DEFAULT 0 NOT NULL,
	`lease_expires_at` integer,
	`last_heartbeat_at` integer,
	`last_error_code` text,
	`cancellation_requested_at` integer,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`completed_at` integer,
	FOREIGN KEY (`cost_operation_id`) REFERENCES `ai_cost_operations`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "ai_jobs_kind_valid" CHECK(length(trim("ai_jobs"."kind")) between 1 and 120 and "ai_jobs"."kind" not glob '*[^a-z0-9.-]*'),
	CONSTRAINT "ai_jobs_payload_version_valid" CHECK("ai_jobs"."payload_version" between 1 and 100),
	CONSTRAINT "ai_jobs_payload_json_valid" CHECK(length("ai_jobs"."payload_json") between 2 and 32768 and json_valid("ai_jobs"."payload_json") and json_type("ai_jobs"."payload_json") = 'object'),
	CONSTRAINT "ai_jobs_payload_hash_valid" CHECK(length("ai_jobs"."payload_hash") = 64 and "ai_jobs"."payload_hash" not glob '*[^0-9a-f]*'),
	CONSTRAINT "ai_jobs_dedupe_key_valid" CHECK(length(trim("ai_jobs"."dedupe_key")) between 1 and 240),
	CONSTRAINT "ai_jobs_cost_center_valid" CHECK("ai_jobs"."cost_center" in ('STUDENT_GENERATION','KNOWLEDGE_INDEXING','AGENT_2','EVALS','EXPERIMENTS')),
	CONSTRAINT "ai_jobs_priority_valid" CHECK("ai_jobs"."priority" in ('LOW','NORMAL','HIGH','CRITICAL')),
	CONSTRAINT "ai_jobs_status_valid" CHECK("ai_jobs"."status" in ('PENDING','RUNNING','RETRY_WAIT','SUCCEEDED','DEAD_LETTER','CANCELLED')),
	CONSTRAINT "ai_jobs_attempt_count_valid" CHECK("ai_jobs"."attempt_count" between 0 and 100),
	CONSTRAINT "ai_jobs_max_attempts_valid" CHECK("ai_jobs"."max_attempts" between 1 and 100),
	CONSTRAINT "ai_jobs_timeout_valid" CHECK("ai_jobs"."timeout_ms" between 1 and 86400000),
	CONSTRAINT "ai_jobs_lease_duration_valid" CHECK("ai_jobs"."lease_duration_ms" between 100 and 86400000),
	CONSTRAINT "ai_jobs_backoff_valid" CHECK("ai_jobs"."backoff_base_ms" between 0 and 86400000 and "ai_jobs"."backoff_max_ms" between "ai_jobs"."backoff_base_ms" and 86400000),
	CONSTRAINT "ai_jobs_scheduled_nonnegative" CHECK("ai_jobs"."scheduled_at" >= 0),
	CONSTRAINT "ai_jobs_lease_generation_valid" CHECK("ai_jobs"."lease_generation" >= 0),
	CONSTRAINT "ai_jobs_lease_owner_valid" CHECK("ai_jobs"."lease_owner" is null or length(trim("ai_jobs"."lease_owner")) between 1 and 200),
	CONSTRAINT "ai_jobs_lease_token_valid" CHECK("ai_jobs"."lease_token" is null or length(trim("ai_jobs"."lease_token")) between 1 and 200),
	CONSTRAINT "ai_jobs_last_error_valid" CHECK("ai_jobs"."last_error_code" is null or length(trim("ai_jobs"."last_error_code")) between 1 and 120),
	CONSTRAINT "ai_jobs_created_nonnegative" CHECK("ai_jobs"."created_at" >= 0),
	CONSTRAINT "ai_jobs_updated_ordered" CHECK("ai_jobs"."updated_at" >= "ai_jobs"."created_at"),
	CONSTRAINT "ai_jobs_completed_valid" CHECK("ai_jobs"."completed_at" is null or "ai_jobs"."completed_at" >= "ai_jobs"."created_at"),
	CONSTRAINT "ai_jobs_lease_fields_valid" CHECK(("ai_jobs"."status" = 'RUNNING' and "ai_jobs"."lease_owner" is not null and "ai_jobs"."lease_token" is not null and "ai_jobs"."lease_expires_at" is not null and "ai_jobs"."last_heartbeat_at" is not null and "ai_jobs"."lease_generation" >= 1) or ("ai_jobs"."status" <> 'RUNNING' and "ai_jobs"."lease_owner" is null and "ai_jobs"."lease_token" is null and "ai_jobs"."lease_expires_at" is null and "ai_jobs"."last_heartbeat_at" is null))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ai_jobs_kind_dedupe_unique` ON `ai_jobs` (`kind`,`dedupe_key`);--> statement-breakpoint
CREATE INDEX `ai_jobs_claim_index` ON `ai_jobs` (`status`,`scheduled_at`,`priority`,`created_at`);--> statement-breakpoint
CREATE INDEX `ai_jobs_lease_index` ON `ai_jobs` (`status`,`lease_expires_at`);--> statement-breakpoint
CREATE INDEX `ai_jobs_cost_operation_index` ON `ai_jobs` (`cost_operation_id`);--> statement-breakpoint
CREATE TABLE `ai_outbox_events` (
	`id` text PRIMARY KEY NOT NULL,
	`event_type` text NOT NULL,
	`payload_version` integer NOT NULL,
	`payload_json` text NOT NULL,
	`payload_hash` text NOT NULL,
	`dedupe_key` text NOT NULL,
	`status` text NOT NULL,
	`scheduled_at` integer NOT NULL,
	`dispatched_job_id` text,
	`safe_error_code` text,
	`created_at` integer NOT NULL,
	`dispatched_at` integer,
	FOREIGN KEY (`dispatched_job_id`) REFERENCES `ai_jobs`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "ai_outbox_events_type_valid" CHECK(length(trim("ai_outbox_events"."event_type")) between 1 and 120 and "ai_outbox_events"."event_type" not glob '*[^a-z0-9.-]*'),
	CONSTRAINT "ai_outbox_events_payload_version_valid" CHECK("ai_outbox_events"."payload_version" between 1 and 100),
	CONSTRAINT "ai_outbox_events_payload_json_valid" CHECK(length("ai_outbox_events"."payload_json") between 2 and 32768 and json_valid("ai_outbox_events"."payload_json") and json_type("ai_outbox_events"."payload_json") = 'object'),
	CONSTRAINT "ai_outbox_events_payload_hash_valid" CHECK(length("ai_outbox_events"."payload_hash") = 64 and "ai_outbox_events"."payload_hash" not glob '*[^0-9a-f]*'),
	CONSTRAINT "ai_outbox_events_dedupe_key_valid" CHECK(length(trim("ai_outbox_events"."dedupe_key")) between 1 and 240),
	CONSTRAINT "ai_outbox_events_status_valid" CHECK("ai_outbox_events"."status" in ('PENDING','DISPATCHED','FAILED','CANCELLED')),
	CONSTRAINT "ai_outbox_events_scheduled_nonnegative" CHECK("ai_outbox_events"."scheduled_at" >= 0),
	CONSTRAINT "ai_outbox_events_error_valid" CHECK("ai_outbox_events"."safe_error_code" is null or length(trim("ai_outbox_events"."safe_error_code")) between 1 and 120),
	CONSTRAINT "ai_outbox_events_created_nonnegative" CHECK("ai_outbox_events"."created_at" >= 0),
	CONSTRAINT "ai_outbox_events_dispatched_valid" CHECK(("ai_outbox_events"."status" = 'DISPATCHED' and "ai_outbox_events"."dispatched_job_id" is not null and "ai_outbox_events"."dispatched_at" is not null) or ("ai_outbox_events"."status" <> 'DISPATCHED' and "ai_outbox_events"."dispatched_job_id" is null and "ai_outbox_events"."dispatched_at" is null))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ai_outbox_events_type_dedupe_unique` ON `ai_outbox_events` (`event_type`,`dedupe_key`);--> statement-breakpoint
CREATE INDEX `ai_outbox_events_dispatch_index` ON `ai_outbox_events` (`status`,`scheduled_at`,`created_at`);