/**
 * entities/index.ts
 * =================
 * Core Entity Model for the Pythagoras Platform.
 *
 * Every entity is a first-class citizen with:
 *   - UUID (auto-generated by Firestore)
 *   - Readable ID (optional, human-friendly)
 *   - Metadata (audit info, timestamps)
 *   - Future extensibility
 *
 * Design principles:
 *   1. Never tightly couple unrelated information
 *   2. Every entity references registry IDs (never hardcoded strings)
 *   3. Every entity supports versioning
 *   4. Every entity can exist independently
 *
 * Hierarchy:
 *   Subject → Section → Topic → Package → Question
 *                                    ↕
 *                                 Resource
 *
 * Cross-cutting:
 *   Source, Tag, Registry (shared across entities)
 */

// ============================================================
// Base types
// ============================================================

/** Audit information attached to every entity. */
export interface AuditInfo {
  createdAt: string | null;
  updatedAt: string | null;
  createdBy: string | null;
  updatedBy: string | null;
}

/** Metadata common to all entities. */
export interface BaseEntity {
  /** Firestore auto-generated ID. */
  id: string;
  /** Human-readable ID (optional, e.g. "biology-chapter-1-q042"). */
  readableId?: string;
  /** Audit information. */
  createdAt?: string | null;
  updatedAt?: string | null;
  createdBy?: string | null;
  updatedBy?: string | null;
}

/** Schema version for migration support. */
export interface Versioned {
  schemaVersion: number;
}

// ============================================================
// Subject — a school subject (Biology, Math, Physics, etc.)
// ============================================================

export interface Subject extends BaseEntity, Versioned {
  /** Display name in Arabic (e.g. "الأحياء"). */
  name: string;
  /** English name (e.g. "Biology"). */
  englishName: string;
  /** Icon key from the icon registry. */
  iconKey: string;
  /** Accent color (CSS value, e.g. "#166534" or "oklch(...)"). */
  color: string;
  /** Whether the subject is available to students. */
  available: boolean;
  /** Sort order. */
  order: number;
  /** Subject description (optional). */
  description?: string;
}

// ============================================================
// Section — a major division within a subject (e.g. Chapter 1)
// ============================================================

export interface Section extends BaseEntity, Versioned {
  /** Parent subject ID. */
  subjectId: string;
  /** Display name in Arabic. */
  name: string;
  /** English name. */
  englishName?: string;
  /** Sort order within subject. */
  order: number;
  /** Whether the section is available. */
  available: boolean;
}

// ============================================================
// Topic — a specific topic within a section
// ============================================================

export interface Topic extends BaseEntity, Versioned {
  /** Parent section ID. */
  sectionId: string;
  /** Grandparent subject ID (denormalized for queries). */
  subjectId: string;
  /** Display name in Arabic. */
  name: string;
  /** Sort order within section. */
  order: number;
}

// ============================================================
// Package Status lifecycle
// ============================================================

export type PackageStatus =
  | "draft"
  | "review"
  | "ready"
  | "published"
  | "archived"
  | "hidden";

// ============================================================
// Package — a collection of questions (like an exam or study set)
// ============================================================

export interface Package extends BaseEntity, Versioned {
  /** Display name (e.g. "مراجعة شاملة - الفصل الأول"). */
  name: string;
  /** Description (optional). */
  description?: string;
  /** Subject ID (references Subject entity). */
  subjectId: string;
  /** Section ID (references Section entity). */
  sectionId: string;
  /** Topic ID (optional, references Topic entity). */
  topicId?: string;
  /** Package icon key. */
  iconKey: string;
  /** Accent color. */
  color: string;
  /** Current status in the lifecycle. */
  status: PackageStatus;
  /** Package version (incremented on each publish). */
  version: number;
  /** Question count (denormalized for fast display). */
  questionCount: number;
  /** Resource count (denormalized). */
  resourceCount: number;
  /** Whether the package is visible to students. */
  visible: boolean;
  /** Sort order. */
  order: number;
  /** Tags (references Tag entities by ID). */
  tags: string[];
  /** Last published timestamp. */
  publishedAt?: string | null;
  /** Last validation status. */
  validationStatus?: "valid" | "invalid" | "pending";
  /** Validation errors count. */
  validationErrors?: number;
}

// ============================================================
// Question Type — registry-defined type (MCQ, fill-blank, etc.)
// ============================================================

export type QuestionTypeValue =
  | "mcq"
  | "fill-blank"
  | "true-false"
  | "short-answer"
  | "long-answer"
  | "essay"
  | "matching"
  | "ordering"
  | "diagram"
  | "custom";

// ============================================================
// Source — where a question appeared (Ministerial, TV, etc.)
// ============================================================

export type SourceType =
  | "ministerial"
  | "educational-tv"
  | "chapter-end"
  | "discussion"
  | "enrichment"
  | "custom";

export interface Source extends BaseEntity, Versioned {
  /** Source type (references registry). */
  type: SourceType;
  /** Display name (e.g. "امتحان وزاري 2024"). */
  name: string;
  /** Year (for ministerial exams). */
  year?: number;
  /** Session (first/second). */
  session?: "first" | "second";
  /** Additional notes. */
  notes?: string;
}

// ============================================================
// Question Appearance — a question's presence in a specific source
// ============================================================

export interface QuestionAppearance {
  /** Source ID (references Source entity). */
  sourceId: string;
  /** Source type (denormalized for queries). */
  sourceType: SourceType;
  /** Year (denormalized). */
  year?: number;
  /** Session (denormalized). */
  session?: "first" | "second";
  /** Question number in that source (optional). */
  questionNumber?: number;
}

// ============================================================
// Resource — an image, drawing, table, etc. attached to a question
// ============================================================

export type ResourceType =
  | "image"
  | "drawing"
  | "svg"
  | "table"
  | "audio"
  | "video"
  | "pdf"
  | "animation"
  | "interactive"
  | "custom";

export interface Resource extends BaseEntity, Versioned {
  /** Resource type. */
  type: ResourceType;
  /** Display name. */
  name: string;
  /** Cloud Storage path (e.g. "content/questions/bio-q042-diagram.png"). */
  storagePath: string;
  /** MIME type. */
  mimeType: string;
  /** File size in bytes. */
  sizeBytes: number;
  /** Width in pixels (for images/videos). */
  width?: number;
  /** Height in pixels. */
  height?: number;
  /** Alt text for accessibility. */
  altText?: string;
  /** Caption (shown below the resource). */
  caption?: string;
  /** Whether this resource is shared across multiple questions. */
  shared: boolean;
  /** Usage count (how many questions reference it). */
  usageCount: number;
}

// ============================================================
// Question — the core entity of the platform
// ============================================================

export type QuestionStatus =
  | "draft"
  | "review"
  | "ready"
  | "published"
  | "archived"
  | "hidden";

export type DifficultyLevel =
  | "easy"
  | "medium"
  | "hard"
  | "expert";

/**
 * Question Entity — designed as independent modules.
 * Each module is independent and can be extended without affecting others.
 */
export interface Question extends BaseEntity, Versioned {
  // ---- Identity Module ----
  /** Package this question belongs to. */
  packageId: string;
  /** Subject ID (denormalized for queries). */
  subjectId: string;
  /** Section ID (denormalized). */
  sectionId: string;
  /** Topic ID (optional). */
  topicId?: string;
  /** Question number within the package. */
  order: number;

  // ---- Content Module ----
  /** The question text (Arabic, supports markdown). */
  questionText: string;
  /** Question type (references registry). */
  type: QuestionTypeValue;
  /** Answer text (supports markdown). */
  answerText: string;
  /** MCQ options (if type is "mcq"). */
  options?: string[];
  /** Index of correct option (for MCQ). */
  correctOptionIndex?: number;
  /** Explanation (shown after answering). */
  explanation?: string;

  // ---- Classification Module ----
  /** Difficulty level. */
  difficulty: DifficultyLevel;
  /** Tags (references Tag entities by ID). */
  tags: string[];
  /** Appearances (which sources this question appeared in). */
  appearances: QuestionAppearance[];

  // ---- Resources Module ----
  /** Resource IDs attached to this question. */
  resourceIds: string[];

  // ---- Status Module ----
  /** Current status. */
  status: QuestionStatus;
  /** Whether the question is visible to students. */
  visible: boolean;
  /** Question version (incremented on each edit). */
  version: number;

  // ---- Search Module ----
  /** Normalized search text (for full-text search). */
  searchText?: string;
  /** Search keywords extracted from the question. */
  keywords?: string[];

  // ---- Analytics Module (denormalized) ----
  /** Times answered. */
  timesAnswered?: number;
  /** Times answered correctly. */
  timesCorrect?: number;
}

// ============================================================
// Tag — for flexible categorization
// ============================================================

export interface Tag extends BaseEntity {
  /** Tag name (Arabic). */
  name: string;
  /** Tag color. */
  color: string;
  /** Usage count. */
  usageCount: number;
}

// ============================================================
// Registry Entry — a single entry in a global registry
// ============================================================

export interface RegistryEntry extends BaseEntity {
  /** Registry name (e.g. "subjects", "question-types", "sources"). */
  registry: string;
  /** Entry key (e.g. "biology", "mcq", "ministerial"). */
  key: string;
  /** Display name (Arabic). */
  label: string;
  /** English label. */
  englishLabel?: string;
  /** Icon key. */
  iconKey?: string;
  /** Color. */
  color?: string;
  /** Sort order. */
  order: number;
  /** Whether this entry is active. */
  active: boolean;
  /** Additional metadata (flexible). */
  metadata?: Record<string, unknown>;
}

// ============================================================
// History — audit trail for any entity change
// ============================================================

export interface HistoryEntry extends BaseEntity {
  /** Entity type that was changed (e.g. "question", "package"). */
  entityType: string;
  /** Entity ID that was changed. */
  entityId: string;
  /** Action performed (created, updated, deleted, published, etc.). */
  action: string;
  /** Field-level changes (before → after). */
  changes?: Record<string, { before: unknown; after: unknown }>;
  /** User who performed the action. */
  userId: string;
  /** User display name. */
  userName?: string;
  /** Snapshot of the entity before the change (optional). */
  snapshot?: Record<string, unknown>;
}

// ============================================================
// Re-exports
// ============================================================

export type {
  BaseEntity as default,
};
