const fence = String.fromCharCode(96).repeat(3);
const block = (language: string, code: string) => `${fence}${language}\n${code}\n${fence}`;
export const PREVIEW_HEIGHT_TAIL_FIXTURE = [
  block('text', 'Block 1'), block('python', 'print(2)'),
  block('html', '<p>HTML preview — كتلة قصيرة</p>'), block('json', '{"block":4}'),
  block('typescript', 'const block = 5;'), block('mermaid', 'flowchart LR\n  A[Source] --> B[Preview]'),
  block('bash', 'printf "block 7\\n"'), block('swift', 'let block = 8'),
  block('custom-dsl', 'Block 9 — Unknown Language\nالمصدر الأخير كامل.'), 'انتهى اختبار العرض.',
].join('\n\n');
export const LONG_USER_FIXTURE = Array.from({ length: 26 }, (_, i) => `المطلب ${i + 1}: اشرح العلاقة بين API وTypeScript والمصطلح Newton's Second Law مع مثال عربي واضح، وحافظ على خطوات الحل كاملة.`).join('\n');
export const CHAT_QUALITY_CASES = [
  { title: 'Completed preview tail — nine code blocks', markdown: PREVIEW_HEIGHT_TAIL_FIXTURE },
  { title: 'Plain text fence', markdown: block('text', 'First line\n  Indented line\nآخر سطر') },
  { title: 'Python fence', markdown: block('python', 'def average(values):\n    return sum(values) / len(values)\n\nprint("مرحبا")') },
  { title: 'JSON fence', markdown: block('json', '{\n  "name": "Pi",\n  "message": "مرحبا",\n  "enabled": true\n}') },
  { title: 'TypeScript fence', markdown: block('typescript', 'type Student = { id: string; name: string };\nconst greet = (student: Student): string => `مرحبا ${student.name}`;') },
  { title: 'HTML fence', markdown: block('html', '<section class="lesson">\n  <article>\n    <h2>الدرس الأول</h2>\n  </article>\n</section>') },
  { title: 'Bash fence', markdown: block('bash', '#!/usr/bin/env bash\nprintf "%s\\n" "hello world"\nexport SUBJECT="physics"') },
  { title: 'Unknown language', markdown: block('custom-dsl', '  literal content\n`` inside a code line') },
  { title: 'No language', markdown: block('', 'Language-free text') },
  { title: 'Tabs + indentation + Unicode code', markdown: block('ts', '\tinterface Student {\n\t\tname: string; // مرحبا 👋\n\t}\n  const student = { name: "Pi" };  ') },
  { title: 'SwiftUI language family fence', markdown: block('swiftui', 'import SwiftUI\nstruct Lesson: View {\n  let title = "مرحبا"\n  var body: some View { Text(title) }\n}') },
  { title: 'JSONC comments fence', markdown: block('jsonc', '{\n  // Optional settings\n  "enabled": true,\n  "limit": 42\n}') },
  { title: 'PowerShell fence', markdown: block('ps1', '# A local example\n$student = "Pi"\nWrite-Output $student') },
  { title: 'INI / env language family fence', markdown: block('.env', '# Example only\nMODE=development\nRETRIES=3') },
  { title: 'Mermaid flowchart fence', markdown: block('mermaid', 'flowchart LR\n  A[Source] --> B[Study]\n  B --> C[Pi]') },
  { title: 'Mermaid sequenceDiagram fence', markdown: block('mermaid', 'sequenceDiagram\n  participant S as Student\n  participant P as Pi\n  S->>P: Explain the lesson\n  P-->>S: Step by step') },
  { title: 'Mermaid classDiagram fence', markdown: block('mermaid', 'classDiagram\n  class Student {\n    +String name\n    +study()\n  }\n  Student --> Lesson') },
  { title: 'Malformed Mermaid fence', markdown: block('mermaid', 'flowchart THIS IS NOT VALID\n  A[missing end') },
  { title: 'Long Mermaid Source / Preview cycle fence', markdown: block('mermaid', 'flowchart LR\n' + Array.from({ length: 120 }, (_, i) => `  Step${i}[Study step ${i + 1}] --> Step${i + 1}[Study step ${i + 2}]`).join('\n')) },
  { title: 'HTML preview fence — semantic, bilingual, inline CSS', markdown: block('html', '<main dir="rtl" style="padding:16px"><article><h2>الدرس الأول — API</h2><p>مثال عربي مع English text.</p><button style="padding:8px;border-radius:8px">ابدأ القراءة</button></article></main>') },
  { title: 'HTML long preview fence', markdown: block('html', '<section>' + Array.from({ length: 40 }, (_, i) => `<p>السطر ${i + 1} — A bounded preview keeps this long document inside its viewport.</p>`).join('\n') + '</section>') },
  { title: 'HTML isolated preview fence — blocked network/navigation/script', markdown: block('html', '<link rel="stylesheet" href="https://example.invalid/blocked.css">\n<img src="https://example.invalid/blocked.png">\n<iframe src="https://example.invalid/blocked-frame"></iframe>\n<a href="https://example.invalid/blocked-link">رابط محظور</a>\n<a href="javascript:alert(1)">JavaScript URL</a>\n<form action="https://example.invalid/blocked-form"><button>Submit</button></form>\n<p id="script-proof">JavaScript must not execute</p>\n<script>document.getElementById("script-proof").textContent="SCRIPT EXECUTED";</script>') },
  { title: 'Empty code block', markdown: fence + 'python\n' + fence },
  { title: 'Long code line — 360 characters', markdown: block('ts', `const value = "${'abcdef'.repeat(60)}";`) },
  { title: 'Independent code blocks / final block', markdown: block('py', 'print(1)') + '\n\nنص بين كتلتين.\n\n' + block('json', '{"result": 2}') },
  { title: 'Wide display math — stress regression', markdown: '$$\nK=\\frac{1}{2}(2.5)(12)^2=\\frac{1}{2}(2.5)(144)=1.25\\times144=180\\,\\mathrm{J}\n$$' },
  { title: 'Extra-wide display math', markdown: '$$\n' + Array.from({ length: 18 }, (_, i) => `\\frac{x^{${i + 1}}}{${i + 2}}`).join('+') + '=F(x)+C\n$$' },
  { title: 'Normal centered equation', markdown: '$$\n\\int_0^2 x\\,dx=2\n$$' },
  { title: 'Inline bidi isolation', markdown: [
    'هذا المصطلح API مهم في التطبيق.', "ينص Newton's Second Law على العلاقة التالية.",
    'نستخدم DNA وRNA وATP داخل الأحياء.', 'يمكن قراءة JSON من TypeScript عبر API.',
    'This English paragraph must keep its original direction.', 'فقرة عربية تعود بعد الإنجليزية.',
    'نص مع `const API = 1` و[رابط API](https://example.com/API) ومعادلة $F(x)$.',
  ].join('\n\n') },
  { title: 'Wide RTL table — preserved', markdown: '| المقارنة | المفهوم الأول | المفهوم الثاني | المفهوم الثالث | المفهوم الرابع | المفهوم الخامس |\n| --- | --- | --- | --- | --- | --- |\n| وصف طويل للمقارنة | محتوى عربي طويل للخانة الأولى | محتوى عربي طويل للخانة الثانية | محتوى عربي طويل للخانة الثالثة | محتوى عربي طويل للخانة الرابعة | محتوى عربي طويل للخانة الخامسة |' },
] as const;
