"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowLeft, ArrowUp, CheckCircle2, FileText, GitBranch, Loader2, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import type { EffectiveQuestionDetail, EffectiveTaxonomyNode, QuestionEditorDraft } from "@/server/question-editor";
import type { QuestionItemContent, QuestionOccurrenceContent, QuestionSourceKind } from "@/server/questions";
import { allocateEditorIds, saveProposal } from "./QuestionPackageEditorWorkspace";
import { RichDocumentEditor } from "./RichDocumentEditor";

const SOURCE_LABELS: Record<QuestionSourceKind, string> = {
  ministerial: "وزاري", "discussion-question": "أسئلة المناقشة", "educational-tv": "التلفزيون التربوي",
  "end-of-chapter": "أسئلة نهاية الفصل", "book-question": "سؤال كتاب", "book-exercise": "تمرين كتاب", enrichment: "إثرائي", other: "أخرى",
};

interface PackageWorkspace { package: { content: { title: string } }; taxonomy: EffectiveTaxonomyNode[]; activeDraft: QuestionEditorDraft | null }

export function QuestionEditorWorkspace({ packageId, questionId, initialOrder = 1 }: { packageId: string; questionId: string; initialOrder?: number }) {
  const router = useRouter();
  const [question, setQuestion] = useState<EffectiveQuestionDetail | null>(null); const [packageWorkspace, setPackageWorkspace] = useState<PackageWorkspace | null>(null); const [value, setValue] = useState<QuestionItemContent | null>(null); const [loading, setLoading] = useState(true); const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const packageResponse = await fetch(`/api/admin/question-editor/packages/${packageId}`, { cache: "no-store" }); const packageBody = await packageResponse.json() as { workspace?: PackageWorkspace }; if (!packageResponse.ok || !packageBody.workspace) throw new Error(); if (questionId === "new") { const primaryTaxonomyId = packageBody.workspace.taxonomy[0]?.id; if (!primaryTaxonomyId) throw new Error(); const ids = await allocateEditorIds(packageId, { blocks: 1 }); const content: QuestionItemContent = { packageId, displayOrder: Math.max(1, initialOrder), primaryVariantId: ids.variantId, taxonomyAssignments: [{ taxonomyNodeId: primaryTaxonomyId, role: "PRIMARY", position: 0 }], variants: [{ id: ids.variantId, displayOrder: 1, content: { type: "doc", version: 1, blocks: [{ id: ids.blockIds[0], type: "paragraph", spans: [{ text: "" }] }] }, occurrences: [] }], sharedAnswer: null }; const localQuestion: EffectiveQuestionDetail = { id: ids.questionId, content, revision: 0, draft: true, draftOnly: true, publishedVariantIds: [], publishedOccurrenceIds: [] }; setQuestion(localQuestion); setValue(content); setPackageWorkspace(packageBody.workspace); setDirty(false); return; } const questionResponse = await fetch(`/api/admin/question-editor/packages/${packageId}/questions/${questionId}`, { cache: "no-store" }); const questionBody = await questionResponse.json() as { question?: EffectiveQuestionDetail }; if (!questionResponse.ok || !questionBody.question) throw new Error(); setQuestion(questionBody.question); setValue(structuredClone(questionBody.question.content)); setPackageWorkspace(packageBody.workspace); setDirty(false); } catch { setMessage("تعذّر تحميل السؤال."); } finally { setLoading(false); } }, [initialOrder, packageId, questionId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const guard = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", guard); return () => window.removeEventListener("beforeunload", guard); }, [dirty]);
  const update = (next: QuestionItemContent) => { setValue(next); setDirty(true); setMessage(null); };
  const allocate = async (kind: "blocks" | "verses", count: number) => { const ids = await allocateEditorIds(packageId, { [kind]: count }); return kind === "blocks" ? ids.blockIds : ids.verseIds; };
  const save = async () => { if (!value || !question) return; setSaving(true); try { await saveProposal(packageId, "question.item", question.id, value); setDirty(false); setMessage("حُفظ السؤال في المسودة؛ المحتوى القانوني لم يتغير."); if (questionId === "new") router.replace(`/admin/questions/${packageId}/questions/${question.id}`); else await load(); } catch { setMessage("تعذّر الحفظ. تحقق من التصنيف الأساسي ومحتوى الصيغ والورود."); } finally { setSaving(false); } };
  if (loading) return <div className="grid min-h-[70vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-primary" /></div>;
  if (!value || !question || !packageWorkspace) return <main className="p-8" dir="rtl"><p className="rounded-xl bg-destructive/10 p-4 text-destructive">{message ?? "السؤال غير موجود."}</p></main>;
  const taxonomy = packageWorkspace.taxonomy;
  const primaryTaxonomy = value.taxonomyAssignments.find((item) => item.role === "PRIMARY")?.taxonomyNodeId;
  return <main className="mx-auto w-full max-w-[1500px] space-y-5 p-4 sm:p-6 lg:p-8" dir="rtl">
    <header className="sticky top-3 z-30 rounded-3xl border bg-background/95 p-4 shadow-sm backdrop-blur supports-[backdrop-filter]:bg-background/85"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><Link href={`/admin/questions/${packageId}`} onClick={(event) => { if (dirty && !window.confirm("لديك تغييرات غير محفوظة. هل تريد المغادرة؟")) event.preventDefault(); }} className="inline-flex items-center gap-1 text-xs text-muted-foreground"><ArrowLeft className="h-3.5 w-3.5" /> {packageWorkspace.package.content.title}</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-xl font-black">سؤال #{value.displayOrder}</h1>{question.draft ? <span className="rounded-full bg-sky-500/10 px-2.5 py-1 text-[10px] font-bold text-sky-600">غير منشور</span> : <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-[10px] font-bold text-emerald-600">منشور</span>}{dirty ? <span className="rounded-full bg-amber-500/10 px-2.5 py-1 text-[10px] font-bold text-amber-600">تغييرات محلية</span> : null}</div><p className="mt-1 truncate text-[10px] text-muted-foreground">{primaryTaxonomy ? breadcrumb(primaryTaxonomy, taxonomy) : "يلزم تصنيف PRIMARY"}</p></div><div className="flex flex-wrap gap-2">{packageWorkspace.activeDraft ? <Button variant="outline" asChild><Link href={`/admin/review/${packageWorkspace.activeDraft.id}`}><ShieldCheck className="h-4 w-4" /> فتح المراجعة</Link></Button> : null}<Button disabled={!dirty || saving} onClick={() => void save()}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />} حفظ في المسودة</Button></div></div>{message ? <p className="mt-3 rounded-xl bg-muted/50 p-3 text-xs">{message}</p> : null}</header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]"><section className="min-w-0 rounded-3xl border bg-card p-4 sm:p-6"><Tabs defaultValue="variants" dir="rtl"><TabsList className="grid h-auto w-full grid-cols-3"><TabsTrigger value="variants">الصيغ</TabsTrigger><TabsTrigger value="answer">الجواب المشترك</TabsTrigger><TabsTrigger value="sources">المصادر</TabsTrigger></TabsList><TabsContent value="variants" className="mt-5"><VariantsEditor value={value} onChange={update} publishedVariantIds={question.publishedVariantIds} packageId={packageId} allocate={allocate} /></TabsContent><TabsContent value="answer" className="mt-5">{value.sharedAnswer ? <><RichDocumentEditor label="الجواب المشترك" value={value.sharedAnswer} onChange={(sharedAnswer) => update({ ...value, sharedAnswer })} allocateIds={allocate} /><Button className="mt-3" variant="outline" onClick={() => update({ ...value, sharedAnswer: null })}>إزالة الجواب من المسودة</Button></> : <div className="grid min-h-64 place-items-center rounded-2xl border border-dashed text-center"><div><FileText className="mx-auto h-9 w-9 text-primary/50" /><p className="mt-3 text-sm font-bold">لا يوجد جواب مشترك</p><p className="mt-1 text-xs text-muted-foreground">غياب الجواب مسموح ويظهر بوضوح في المراجعة.</p><Button className="mt-4" onClick={async () => { const [id] = await allocate("blocks", 1); update({ ...value, sharedAnswer: { type: "doc", version: 1, blocks: [{ id, type: "paragraph", spans: [{ text: "" }] }] } }); }}><Plus className="h-4 w-4" /> إنشاء جواب</Button></div></div>}</TabsContent><TabsContent value="sources" className="mt-5"><OccurrencesWorkspace value={value} onChange={update} publishedOccurrenceIds={question.publishedOccurrenceIds} packageId={packageId} /></TabsContent></Tabs></section><aside className="space-y-4"><QuestionMetadata value={value} onChange={update} taxonomy={taxonomy} /><section className="rounded-3xl border bg-card p-4"><h2 className="text-sm font-black">هوية تقنية</h2><dl className="mt-3 space-y-2"><Info label="Question UUID" value={question.id} /><Info label="Entity revision" value={String(question.revision)} /><Info label="Variants" value={String(value.variants.length)} /><Info label="Occurrences" value={String(value.variants.reduce((sum, item) => sum + item.occurrences.length, 0))} /></dl></section></aside></div>
  </main>;
}

function VariantsEditor({ value, onChange, publishedVariantIds, packageId, allocate }: { value: QuestionItemContent; onChange: (value: QuestionItemContent) => void; publishedVariantIds: string[]; packageId: string; allocate: (kind: "blocks" | "verses", count: number) => Promise<string[]> }) {
  const [selected, setSelected] = useState(value.primaryVariantId); const selectedId = value.variants.some((item) => item.id === selected) ? selected : value.primaryVariantId; const variant = value.variants.find((item) => item.id === selectedId) ?? value.variants[0];
  const move = (id: string, direction: -1 | 1) => { const index = value.variants.findIndex((item) => item.id === id); const target = index + direction; if (target < 0 || target >= value.variants.length) return; const variants = [...value.variants]; [variants[index], variants[target]] = [variants[target], variants[index]]; onChange({ ...value, variants: variants.map((item, position) => ({ ...item, displayOrder: position + 1 })) }); };
  const add = async () => { const ids = await allocateEditorIds(packageId, { blocks: 1 }); const next = { id: ids.variantId, displayOrder: value.variants.length + 1, content: { type: "doc" as const, version: 1 as const, blocks: [{ id: ids.blockIds[0], type: "paragraph" as const, spans: [{ text: "" }] }] }, occurrences: [] }; onChange({ ...value, variants: [...value.variants, next] }); setSelected(next.id); };
  if (!variant) return null;
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-2">{value.variants.map((item) => <button type="button" key={item.id} onClick={() => setSelected(item.id)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${item.id === selectedId ? "border-primary bg-primary text-primary-foreground" : "hover:border-primary/40"}`}>الصيغة {item.displayOrder}{item.id === value.primaryVariantId ? " · الأساسية" : ""}</button>)}<Button size="sm" variant="outline" onClick={() => void add()}><Plus className="h-4 w-4" /> صيغة</Button></div><div className="rounded-2xl bg-muted/20 p-3"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => move(variant.id, -1)}><ArrowUp className="h-3.5 w-3.5" /> أعلى</Button><Button size="sm" variant="outline" onClick={() => move(variant.id, 1)}><ArrowDown className="h-3.5 w-3.5" /> أسفل</Button></div><div className="flex gap-2"><Button size="sm" variant={variant.id === value.primaryVariantId ? "secondary" : "outline"} onClick={() => onChange({ ...value, primaryVariantId: variant.id })}><CheckCircle2 className="h-3.5 w-3.5" /> تعيين كأساسية</Button>{publishedVariantIds.includes(variant.id) ? <Button size="sm" variant="ghost" disabled title="حذف الصيغ المنشورة غير مدعوم في M13">لا يمكن حذف صيغة منشورة</Button> : value.variants.length > 1 ? <Button size="sm" variant="destructive" onClick={() => { const variants = value.variants.filter((item) => item.id !== variant.id).map((item, index) => ({ ...item, displayOrder: index + 1 })); onChange({ ...value, variants, primaryVariantId: value.primaryVariantId === variant.id ? variants[0].id : value.primaryVariantId }); setSelected(variants[0].id); }}><Trash2 className="h-3.5 w-3.5" /> حذف الجديدة</Button> : null}</div></div><RichDocumentEditor label={`محتوى الصيغة ${variant.displayOrder}`} value={variant.content} onChange={(content) => onChange({ ...value, variants: value.variants.map((item) => item.id === variant.id ? { ...item, content } : item) })} allocateIds={allocate} /></div></div>;
}

function OccurrencesWorkspace({ value, onChange, publishedOccurrenceIds, packageId }: { value: QuestionItemContent; onChange: (value: QuestionItemContent) => void; publishedOccurrenceIds: string[]; packageId: string }) {
  const updateVariant = (variantId: string, occurrences: QuestionOccurrenceContent[]) => onChange({ ...value, variants: value.variants.map((item) => item.id === variantId ? { ...item, occurrences } : item) });
  return <div className="space-y-5">{value.variants.map((variant) => <section key={variant.id} className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-black">مصادر الصيغة {variant.displayOrder}</h3><p className="mt-1 text-[10px] text-muted-foreground">rawLabel مستقل ولا يُعاد توليده من الحقول المنظمة.</p></div><Button size="sm" variant="outline" onClick={async () => { const ids = await allocateEditorIds(packageId, { occurrences: 1 }); const next: QuestionOccurrenceContent = { id: ids.occurrenceIds[0], displayOrder: variant.occurrences.length + 1, sourceKind: "other", year: null, roundCode: null, session: null, sourceName: null, notes: null, rawLabel: "", branches: [], qualifiers: [] }; updateVariant(variant.id, [...variant.occurrences, next]); }}><Plus className="h-4 w-4" /> مصدر</Button></div><div className="mt-4 space-y-3">{variant.occurrences.map((occurrence, index) => <OccurrenceEditor key={occurrence.id} value={occurrence} published={publishedOccurrenceIds.includes(occurrence.id)} onChange={(next) => updateVariant(variant.id, variant.occurrences.map((item) => item.id === occurrence.id ? next : item))} onRemove={() => updateVariant(variant.id, variant.occurrences.filter((item) => item.id !== occurrence.id).map((item, position) => ({ ...item, displayOrder: position + 1 })))} onMove={(direction) => { const target = index + direction; if (target < 0 || target >= variant.occurrences.length) return; const occurrences = [...variant.occurrences]; [occurrences[index], occurrences[target]] = [occurrences[target], occurrences[index]]; updateVariant(variant.id, occurrences.map((item, position) => ({ ...item, displayOrder: position + 1 }))); }} />)}{!variant.occurrences.length ? <p className="rounded-xl border border-dashed p-5 text-center text-xs text-muted-foreground">لا توجد ورود لهذه الصيغة.</p> : null}</div></section>)}</div>;
}

function OccurrenceEditor({ value, published, onChange, onRemove, onMove }: { value: QuestionOccurrenceContent; published: boolean; onChange: (value: QuestionOccurrenceContent) => void; onRemove: () => void; onMove: (direction: -1 | 1) => void }) {
  return <article className="rounded-2xl bg-muted/25 p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold">ورود #{value.displayOrder}</span><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={() => onMove(-1)}><ArrowUp className="h-3.5 w-3.5" /></Button><Button size="icon" variant="ghost" onClick={() => onMove(1)}><ArrowDown className="h-3.5 w-3.5" /></Button>{published ? <Button size="sm" variant="ghost" disabled>منشور</Button> : <Button size="icon" variant="ghost" onClick={onRemove}><Trash2 className="h-3.5 w-3.5 text-destructive" /></Button>}</div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="نوع المصدر"><select className="h-10 w-full rounded-md border bg-background px-3 text-xs" value={value.sourceKind} onChange={(event) => onChange({ ...value, sourceKind: event.target.value as QuestionSourceKind })}>{Object.entries(SOURCE_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="السنة"><Input type="number" min={1900} max={2200} value={value.year ?? ""} onChange={(event) => onChange({ ...value, year: event.target.value ? Number(event.target.value) : null })} /></Field><Field label="رمز الدور"><Input value={value.roundCode ?? ""} onChange={(event) => onChange({ ...value, roundCode: event.target.value || null })} /></Field><Field label="الجلسة"><Input value={value.session ?? ""} onChange={(event) => onChange({ ...value, session: event.target.value || null })} /></Field><Field label="اسم المصدر"><Input value={value.sourceName ?? ""} onChange={(event) => onChange({ ...value, sourceName: event.target.value || null })} /></Field><Field label="الفروع (افصل بفاصلة)"><Input value={value.branches.join("، ")} onChange={(event) => onChange({ ...value, branches: splitValues(event.target.value) })} /></Field><Field label="المؤهلات (افصل بفاصلة)"><Input value={value.qualifiers.join("، ")} onChange={(event) => onChange({ ...value, qualifiers: splitValues(event.target.value) })} /></Field><div className="sm:col-span-2"><Field label="الوسم الأصلي rawLabel (مطلوب)"><Input value={value.rawLabel} onChange={(event) => onChange({ ...value, rawLabel: event.target.value })} dir="auto" /></Field></div><div className="sm:col-span-2 lg:col-span-3"><Field label="ملاحظات"><Textarea value={value.notes ?? ""} onChange={(event) => onChange({ ...value, notes: event.target.value || null })} /></Field></div></div></article>;
}

function QuestionMetadata({ value, onChange, taxonomy }: { value: QuestionItemContent; onChange: (value: QuestionItemContent) => void; taxonomy: EffectiveTaxonomyNode[] }) {
  const primary = value.taxonomyAssignments.find((item) => item.role === "PRIMARY")?.taxonomyNodeId ?? ""; const related = new Set(value.taxonomyAssignments.filter((item) => item.role === "RELATED").map((item) => item.taxonomyNodeId));
  return <section className="rounded-3xl border bg-card p-4"><h2 className="text-sm font-black">بيانات السؤال</h2><div className="mt-4 space-y-4"><Field label="الترتيب القانوني"><Input type="number" min={1} value={value.displayOrder} onChange={(event) => onChange({ ...value, displayOrder: Number(event.target.value) })} /><p className="mt-1 text-[9px] text-muted-foreground">رقم العرض للطالب لاحقًا سيكون ترتيبًا محليًا بعد الفلترة، لا هذا الحقل.</p></Field><Field label="التصنيف الأساسي"><select className="h-10 w-full rounded-md border bg-background px-3 text-xs" value={primary} onChange={(event) => { const rest = value.taxonomyAssignments.filter((item) => item.role !== "PRIMARY" && item.taxonomyNodeId !== event.target.value); onChange({ ...value, taxonomyAssignments: [{ taxonomyNodeId: event.target.value, role: "PRIMARY" as const, position: 0 }, ...rest.map((item, index) => ({ ...item, position: index + 1 }))] }); }}><option value="">اختر PRIMARY</option>{taxonomy.map((item) => <option key={item.id} value={item.id}>{breadcrumb(item.id, taxonomy)}</option>)}</select></Field><div><Label className="text-xs">تصنيفات مرتبطة</Label><div className="mt-2 max-h-52 space-y-1 overflow-y-auto rounded-xl border p-2">{taxonomy.filter((item) => item.id !== primary).map((item) => <label key={item.id} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-xs hover:bg-muted"><input type="checkbox" checked={related.has(item.id)} onChange={(event) => { const ids = event.target.checked ? [...related, item.id] : [...related].filter((id) => id !== item.id); onChange({ ...value, taxonomyAssignments: [{ taxonomyNodeId: primary, role: "PRIMARY" as const, position: 0 }, ...ids.map((taxonomyNodeId, index) => ({ taxonomyNodeId, role: "RELATED" as const, position: index + 1 }))].filter((item) => item.taxonomyNodeId) }); }} /> {breadcrumb(item.id, taxonomy)}</label>)}</div></div></div></section>;
}

function breadcrumb(id: string, nodes: EffectiveTaxonomyNode[]) { const map = new Map(nodes.map((item) => [item.id, item])); const parts: string[] = []; const seen = new Set<string>(); let current = map.get(id); while (current && !seen.has(current.id)) { seen.add(current.id); parts.unshift(current.label); current = current.parentId ? map.get(current.parentId) : undefined; } return parts.join(" / "); }
function splitValues(value: string) { return value.split(/[،,]/u).map((item) => item.trim()).filter(Boolean); }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label className="mb-2 block text-xs">{label}</Label>{children}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-[9px] text-muted-foreground">{label}</dt><dd className="mt-1 break-all font-mono text-[10px]" dir="ltr">{value}</dd></div>; }
