name: iOS Native Preview XCTest Dispatcher

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  native-preview-validation:
    name: Run Native Preview XCTest on macOS
    uses: Abbashu0/pythagoras-deploy/.github/workflows/ios-preview-tests.yml@77ecd4848ac5c4492eadab7f0ff7a2da5b66bd8c
    with:
      expected_sha: 77ecd4848ac5c4492eadab7f0ff7a2da5b66bd8c
    permissions:
      contents: read
