name: iOS Native Preview XCTest Dispatcher

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  native-preview-validation:
    name: Run Native Preview XCTest on macOS
    uses: Abbashu0/pythagoras-deploy/.github/workflows/ios-preview-tests.yml@3766f4f6a15f5ee314f644f7667401661d6f927f
    with:
      expected_sha: 3766f4f6a15f5ee314f644f7667401661d6f927f
    permissions:
      contents: read
